### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by arpita8** [alexa/skill-sample-nodejs-quiz-game#1]
Hey!!  Can anyone help me with adding images in my Alexa skill responses. I am quiet confused with adding images to my skill

Thanks in advance

**Comment by akersh-s** [comment]
@arpita8 I suggest taking a look at some of the documentation on the SDK (https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs), the developer portal (https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/display-interface-reference), or in the cookbook (https://github.com/alexa/alexa-cookbook/tree/master/display-directive). You can also try posting on the forums for more direct advice (https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) 

Good luck!
