### ISSUE TITLE
Sample Interaction model has issues

### ISSUE THREAD

**Issue by viv1ag** [alexa/skill-sample-nodejs-quiz-game#15]
Dear Alexa team,
When I am following sample quiz game; I am getting this error while saving the interaction model taken from https://github.com/alexa/skill-sample-nodejs-quiz-game/blob/master/instructions/1-voice-user-interface.md
![1](https://user-images.githubusercontent.com/878291/33761015-b5e29cc8-dc2d-11e7-9e27-d1d4752042a0.png)

Once I removed text "AMAZON." from the error code; I got this error:
![2](https://user-images.githubusercontent.com/878291/33761045-d2230cd8-dc2d-11e7-952e-44671a38cedf.png)

Kindly help me to resolve this.

**Comment by JennJin** [comment]
Looks like your language model is set to en_IN. 
AMAZON.US_STATE and AMAZON.US_CITY are not supported in that locale. 

The example code is intended for the en_US language model.
