### ISSUE TITLE
Few warnings

### ISSUE THREAD

**Issue by Veiam** [alexa/skill-sample-nodejs-quiz-game#22]
Hello all,

In index.js

Line 54 `return "The " + formatCasing(property) + " of " + item.StateName + " is <say-as interpret-as='spell-out'>" + item[property] + "</say-as>. "`
and
Line 57 `return "The " + formatCasing(property) + " of " + item.StateName + " is " + item[property] + ". "`
are missing a semicolon at the end.

Also since `return` is being performed on 54 and 57, 55 and 58's `break` is unreachable I believe.

Line 294 `let property = this.attributes["quizproperty"]` is also missing a semicolon at the end.

Line 176 `const counter = 0;`
Line 374 'function getRandomSymbolSpeech(symbol)'
Line 404 `let speechCon = "";`
These all three are defined but never used within the js.
Is this intended?

**Comment by franklin-lobb** [comment]
Thanks for pointing these out.  I've double-checked the current code and it looks like these have all been fixed.
