### ISSUE TITLE
Purpose of formatCasing?

### ISSUE THREAD

**Issue by marcusx** [alexa/skill-sample-nodejs-quiz-game#30]
What does `formatCasing` exactly do? Does the regex split on non letter characters and replaces it with a space?

Could you provide a docblock for the helper functions?

```
function formatCasing(key)
{
    key = key.split(/(?=[A-Z])/).join(" ");
    return key;
}
```

See: https://github.com/alexa/skill-sample-nodejs-quiz-game/blob/bfbcbfe092fa2ff10f5bdcd8eeff66902ac1a027/lambda/custom/index.js#L400

**Comment by campionfellin** [comment]
I believe that what this does here is split all capital letters with a space. This helps for when Alexa is reading out the questions. For example, you'll see:

https://github.com/alexa/skill-sample-nodejs-quiz-game/blob/bfbcbfe092fa2ff10f5bdcd8eeff66902ac1a027/lambda/custom/index.js#L25

And in some cases, the `property` here is `StateName`, `StatehoodYear`, and `StatehoodOrder`.
This takes them and converts it to `State Name`, `Statehood Year`, and `Statehood Order` for Alexa to read out.
