### ISSUE TITLE
There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by aipauley** [alexa/skill-sample-nodejs-quiz-game#33]
I am trying to complete this example.  I can't get past the first audio statement using the simulator.  It seems to be hanging before the reprompt, since I hear "Welcome to the United States Quiz Game!... " portion. 

No matter what I submit, I can't get past this point.

{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak> Welcome to the United States Quiz Game!  You can ask me about any of the fifty states and their capitals, or you can ask me to start a quiz.  What would you like to do? </speak>"
			},
			"reprompt": {
				"outputSpeech": {
					"type": "SSML",
					"ssml": "<speak> I know lots of things about the United States.  You can ask me about a state or a capital, and I'll tell you what I know.  You can also test your knowledge by asking me to start a quiz.  What would you like to do? </speak>"
				}
			},
			"shouldEndSession": false
		},
		"sessionAttributes": {
			"STATE": "_START"
		},
		"userAgent": "ask-nodejs/1.0.25 Node/v6.10.3"
	}
}

**Comment by wmegel** [comment]
I've got the same problem.
I can start the Quiz game but when Alexa Simulator respond with the first question, the simulator say "there was a problem with the requested skill's answer".
Here is the answer that cause the problem :
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak> OK.  I will ask you 10 questions about the United States. Here is your 1th question.  What is the Abbreviation of North Carolina? </speak>"
			},
			"directives": [
				{
					"type": "Display.RenderTemplate",
					"template": {
						"type": "ListTemplate1",
						"token": "QUESTION",
						"backgroundImage": {
							"sources": [
								{
									"url": "https://m.media-amazon.com/images/G/01/mobile-apps/dex/alexa/alexa-skills-kit/tutorials/quiz-game/state_flag/1024x600/NC._TTH_.png",
									"widthPixels": 0,
									"heightPixels": 0
								}
							]
						},
						"listItems": [
							{
								"token": "CA",
								"textContent": {
									"primaryText": {
										"type": "PlainText",
										"text": "CA"
									}
								}
							},
							{
								"token": "AL",
								"textContent": {
									"primaryText": {
										"type": "PlainText",
										"text": "AL"
									}
								}
							},
							{
								"token": "NC",
								"textContent": {
									"primaryText": {
										"type": "PlainText",
										"text": "NC"
									}
								}
							}
						],
						"title": "Question #1"
					}
				}
			],
			"reprompt": {
				"outputSpeech": {
					"type": "SSML",
					"ssml": "<speak> Here is your 1th question.  What is the Abbreviation of North Carolina? </speak>"
				}
			},
			"shouldEndSession": false
		},
		"sessionAttributes": {
			"quizscore": 0,
			"quizproperty": "Abbreviation",
			"response": "OK.  I will ask you 10 questions about the United States. ",
			"STATE": "_QUIZ",
			"counter": 1,
			"quizitem": {
				"StateName": "North Carolina",
				"Abbreviation": "NC",
				"Capital": "Raleigh",
				"StatehoodYear": 1789,
				"StatehoodOrder": 12
			}
		},
		"userAgent": "ask-nodejs/1.0.25 Node/v6.10.3"
	}
}

**Comment by wmegel** [comment]
Sorry, I founded the source of the problem.
Maybe it can help someone.
This tutorial need us to activate 'Display Interface' in the interfaces panel.

**Comment by aipauley** [comment]
Sorry, where is interfaces panel?

**Comment by wmegel** [comment]
On the left Menu, under "JSON Editor" you have "Interfaces".
Click on it on activate "Display Interface". Then, rebuild your Skill.

**Comment by aipauley** [comment]
Thanks

**Comment by aipauley** [comment]
Could I ask another question?  Where does this skill get the information on
each state, other than the abbreviation - I see that in the slot.  But I
can't find any of the other data.

Thx

**Comment by aipauley** [comment]
Thanks.  I found it after sending you the email.  Couldn't figure why the
abbreviations were the only things loaded into the slots.  Threw me off.

**Comment by adi701** [comment]
can someone tell me how to introduce a pause tag after each question such that it doesn't show in the card output .

eg : What is the Abbreviation of North Carolina <pause = '2sec'/> should not come in the card

possible solutions please

**Comment by akersh-s** [comment]
@wmegel  Thanks! FYI just merged a PR #34 with an update to the instructions

@adi701: Take a look at this topic on the forums: https://forums.developer.amazon.com/questions/74064/how-to-use-ssml-on-node-with-lambda.html

**Comment by minlare** [comment]
To get detailed error logs for this type of error do the following: 

In the Alexa skill page, click on test, type an utterance, and you'll see your request, and possibly response (if your code successfully generates one). Copy the request, go to your lambda code and configure a new test event, paste the request in there and hit save and test.

The result should show you what went wrong or at least what line of code to look at/near.
