### ISSUE TITLE
"The remote endpoint could not be called, or the response it returned was invalid,"

### ISSUE THREAD

**Issue by j839t755** [alexa/skill-sample-nodejs-quiz-game#4]
Hi, I'm having trouble with this error. I've looked on github, stackoverflow, and other cites and can't figure it out. I ran an execution test and it came back successful, but whenever I try to test it in the developer portal I continue to get the "The remote endpoint could not be called, or the response it returned was invalid," error. Could someone please advise me to what I should do to fix it? Thank you in advance!

**Comment by tkb1013** [comment]
Amazon has addressed this issue here: https://forums.developer.amazon.com/articles/79735/ongoing-issue-with-format-of-service-simulator-req.html
